# We might have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-pika-spark"
BBFILE_PATTERN_meta-pika-spark := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-pika-spark = "9"

LAYERDEPENDS_meta-pika-spark = "core freescale-layer"
LAYERSERIES_COMPAT_meta-pika-spark = "kirkstone nanbield scarthgap"
